"""
EcoCart AI System — Streamlit App
Runs the actual task scripts and displays their real outputs.
NCI MSCAI | Fundamentals of AI TABA 2026
"""

import sys, io, os, math, heapq, time, importlib.util
from contextlib import redirect_stdout
from collections import deque

import numpy as np
import pandas as pd
import streamlit as st
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ── page config ───────────────────────────────────────────────────────────────
st.set_page_config(page_title="EcoCart AI", layout="wide",
                   initial_sidebar_state="expanded")

st.markdown("""
<style>
  [data-testid="stAppViewContainer"] { background:#f8fafc; }
  .block-container { padding:1rem 2rem 3rem; }
  .stTabs [data-baseweb="tab"] { font-size:.88rem; font-weight:600; padding:8px 20px; }

  .step-box {
    background:#fff; border-radius:10px; padding:16px 20px;
    box-shadow:0 1px 4px rgba(0,0,0,.08); margin-bottom:12px;
  }
  .step-num {
    display:inline-block; background:#1e293b; color:#fff;
    border-radius:50%; width:26px; height:26px; text-align:center;
    line-height:26px; font-size:.8rem; font-weight:700; margin-right:8px;
  }
  .output-box {
    background:#0f172a; border-radius:8px; padding:14px 18px;
    font-family:monospace; font-size:.82rem; color:#e2e8f0;
    white-space:pre-wrap; margin:8px 0;
  }
  .insight-box {
    background:#f0fdf4; border-left:4px solid #10b981;
    padding:12px 16px; border-radius:0 8px 8px 0; margin:8px 0;
    font-size:.88rem; color:#064e3b;
  }
  .warn-box {
    background:#fff7ed; border-left:4px solid #f59e0b;
    padding:12px 16px; border-radius:0 8px 8px 0; margin:8px 0;
    font-size:.88rem; color:#78350f;
  }
  .info-box {
    background:#eff6ff; border-left:4px solid #3b82f6;
    padding:12px 16px; border-radius:0 8px 8px 0; margin:8px 0;
    font-size:.88rem; color:#1e3a5f;
  }
  div[data-testid="metric-container"] {
    background:#fff; border-radius:10px; padding:12px 16px;
    box-shadow:0 1px 3px rgba(0,0,0,.07);
  }
</style>
""", unsafe_allow_html=True)

# ── colours ───────────────────────────────────────────────────────────────────
BG, SURF, LINE = "#f8fafc", "#ffffff", "#e2e8f0"
FG, MUTE = "#1e293b", "#64748b"
GREEN, BLUE, RED, AMBER = "#10b981", "#3b82f6", "#ef4444", "#f59e0b"

# ── chart helper ──────────────────────────────────────────────────────────────
def _ch(h=380, title=""):
    return dict(height=h, paper_bgcolor=SURF, plot_bgcolor=BG,
                font=dict(color=FG, size=11),
                title=dict(text=title, font=dict(size=13, color=FG), x=0),
                margin=dict(l=50, r=20, t=48, b=40),
                legend=dict(bgcolor=SURF, bordercolor=LINE, borderwidth=1))

# ══════════════════════════════════════════════════════════════════════════════
#  SIDEBAR — navigation guide
# ══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("### EcoCart AI System")
    st.markdown("**How to use this app:**")
    st.markdown("""
1. Click each tab at the top
2. Read the *What is this?* section
3. Press the **Run** button
4. See the real output from the code
5. Read the *What does this tell us?* section
""")
    st.divider()
    st.markdown("**Tasks covered:**")
    st.markdown("🤖 Task 1 — AI Agent Types")
    st.markdown("⚖️ Task 2 — Bias in Segmentation")
    st.markdown("🗺️ Task 3 — Search Algorithms")
    st.markdown("📊 Task 4 — A* vs IDA* Benchmark")
    st.markdown("📈 Task 5 — Demand Forecasting")
    st.markdown("💼 Task 6 — Business Case")
    st.divider()
    st.caption("All outputs in Tasks 2–5 are generated by running the actual task Python scripts.")

# ── header ────────────────────────────────────────────────────────────────────
st.markdown("<h2 style='margin:0 0 16px;color:#1e293b'>EcoCart AI System</h2>",
            unsafe_allow_html=True)

T1, T2, T3, T4, T5, T6 = st.tabs([
    "🤖 Task 1 — AI Agents",
    "⚖️ Task 2 — Bias",
    "🗺️ Task 3 — Routes",
    "📊 Task 4 — A* vs IDA*",
    "📈 Task 5 — Forecast",
    "💼 Task 6 — Business",
])

# ══════════════════════════════════════════════════════════════════════════════
#  TASK 1 — AI AGENTS (interactive simulation)
# ══════════════════════════════════════════════════════════════════════════════
with T1:
    st.markdown("""
<div class='step-box'>
<span class='step-num'>?</span><b>What is this?</b><br><br>
An AI agent is a system that perceives its environment and takes actions to achieve a goal.
EcoCart needs agents that can plan delivery routes, forecast demand, and segment customers.
Three types of agents exist — each making decisions differently. This simulation shows all
three navigating the same delivery map so you can see the difference.
</div>
""", unsafe_allow_html=True)

    # ── agent simulation data ─────────────────────────────────────────────────
    STOPS = {
        "Depot":  (0.0, 0.0, 0), "Shop A": (2.0, 3.0, 3), "Shop B": (5.0, 1.0, 4),
        "Shop C": (7.0, 4.0, 2), "Shop D": (3.0, 6.0, 5), "Shop E": (8.0, 7.0, 1),
        "Shop F": (1.0, 8.0, 3), "Shop G": (6.0, 9.0, 4), "Shop H": (9.0, 2.0, 2),
    }
    def _sd(a, b):
        ax, ay, _ = STOPS[a]; bx, by, _ = STOPS[b]
        return math.hypot(ax - bx, ay - by)

    @st.cache_data
    def _get_routes():
        def reactive():
            r = ["Depot"]; u = [k for k in STOPS if k != "Depot"]; c = "Depot"
            while u:
                nb = min(u, key=lambda n: _sd(c, n)); r.append(nb); u.remove(nb); c = nb
            return r + ["Depot"]
        def goal():
            r = reactive()[:-1]
            td = lambda x: sum(_sd(x[i], x[i+1]) for i in range(len(x)-1)) + _sd(x[-1], x[0])
            ok = True
            while ok:
                ok = False
                for i in range(1, len(r)-1):
                    for j in range(i+1, len(r)):
                        nr = r[:i] + r[i:j+1][::-1] + r[j+1:]
                        if td(nr) < td(r) - 1e-9: r = nr; ok = True
            return r + ["Depot"]
        def utility():
            r = ["Depot"]; u = [k for k in STOPS if k != "Depot"]; c = "Depot"
            while u:
                nb = max(u, key=lambda n: STOPS[n][2] / (_sd(c, n) + .1))
                r.append(nb); u.remove(nb); c = nb
            return r + ["Depot"]
        return {
            "Reactive Agent\n(goes to nearest stop)":   reactive(),
            "Goal-Based Agent\n(plans full route)":     goal(),
            "Utility-Based Agent\n(urgent stops first)": utility(),
        }

    ROUTES = _get_routes()
    RCOLS  = {
        "Reactive Agent\n(goes to nearest stop)":    BLUE,
        "Goal-Based Agent\n(plans full route)":      GREEN,
        "Utility-Based Agent\n(urgent stops first)": AMBER,
    }

    # ── controls ──────────────────────────────────────────────────────────────
    st.markdown("<div class='step-box'><span class='step-num'>1</span>"
                "<b>Pick an agent type and watch it deliver</b></div>",
                unsafe_allow_html=True)

    agent = st.radio("Agent type:", list(ROUTES.keys()), horizontal=True,
                     label_visibility="collapsed")
    ac    = RCOLS[agent]
    route = ROUTES[agent]
    mx    = len(route) - 1

    if st.session_state.get("_ag") != agent:
        st.session_state["_ag"] = agent
        st.session_state["stp"] = 0
        st.session_state["playing"] = False

    stp = st.session_state.get("stp", 0)

    bc1, bc2, bc3, bc4, sld = st.columns([1, 1, 1, 1, 5])
    if bc1.button("⏮", use_container_width=True): stp = 0; st.session_state["playing"] = False
    if bc2.button("◀", use_container_width=True) and stp > 0: stp -= 1; st.session_state["playing"] = False
    if bc3.button("▶", use_container_width=True) and stp < mx: stp += 1; st.session_state["playing"] = False
    playing = st.session_state.get("playing", False)
    if bc4.button("⏸ Pause" if playing else "▶ Play", use_container_width=True):
        st.session_state["playing"] = not playing
    speed = sld.slider("Speed", 1, 8, 3, label_visibility="collapsed")
    stp = st.slider("Step", 0, mx, stp, label_visibility="collapsed", key="stp_slider")
    st.session_state["stp"] = stp

    visited     = set(route[:stp+1])
    path_so_far = route[:stp+1]
    km_done     = sum(_sd(path_so_far[i], path_so_far[i+1]) for i in range(len(path_so_far)-1))

    fig_ag = go.Figure()
    for na in STOPS:
        for nb in STOPS:
            if na >= nb: continue
            x1, y1, _ = STOPS[na]; x2, y2, _ = STOPS[nb]
            if math.hypot(x1-x2, y1-y2) < 5.5:
                fig_ag.add_trace(go.Scatter(x=[x1,x2,None], y=[y1,y2,None], mode="lines",
                    line=dict(color="#e2e8f0", width=1), showlegend=False, hoverinfo="skip"))
    if len(path_so_far) > 1:
        fig_ag.add_trace(go.Scatter(
            x=[STOPS[n][0] for n in path_so_far],
            y=[STOPS[n][1] for n in path_so_far],
            mode="lines+markers", line=dict(color=ac, width=3),
            marker=dict(size=6, color=ac), showlegend=False, hoverinfo="skip"))
    for name, (nx, ny, pri) in STOPS.items():
        if name == "Depot":         nc, sz = "#1e293b", 24
        elif name == route[stp]:    nc, sz = ac, 26
        elif name in visited:       nc, sz = GREEN, 18
        else:                       nc, sz = "#cbd5e1", 16
        lbl = ("⭐ " if pri >= 4 else "") + name.replace("Shop ", "")
        fig_ag.add_trace(go.Scatter(x=[nx], y=[ny], mode="markers+text", showlegend=False,
            marker=dict(size=sz, color=nc, line=dict(color="#fff", width=2)),
            text=[lbl], textposition="top center", textfont=dict(size=9, color=FG),
            hovertemplate=f"<b>{name}</b><br>Priority {pri}/5<extra></extra>"))
    fig_ag.update_layout(**_ch(400, f"Step {stp}/{mx}  —  {km_done:.1f} km traveled"))
    fig_ag.update_xaxes(showgrid=False, showticklabels=False, zeroline=False, range=[-0.5,10.5])
    fig_ag.update_yaxes(showgrid=False, showticklabels=False, zeroline=False, range=[-0.5,10.5])

    map_c, stat_c = st.columns([3, 1])
    with map_c:
        st.plotly_chart(fig_ag, use_container_width=True, key="agent_chart")
    with stat_c:
        st.metric("Steps completed", f"{stp} / {mx}")
        st.metric("Distance so far", f"{km_done:.1f} km")
        st.metric("Total route km", f"{sum(_sd(route[i],route[i+1]) for i in range(len(route)-1)):.2f} km")
        st.markdown(f"<div class='info-box'>"
                    f"⭐ = high priority stop<br>(priority 4 or 5 out of 5)</div>",
                    unsafe_allow_html=True)

    st.markdown("""
<div class='step-box'>
<span class='step-num'>2</span><b>What agent types are shown?</b><br><br>
<b>Reactive:</b> always goes to the nearest unvisited stop. Simple but often takes a longer overall route.<br>
<b>Goal-Based:</b> plans the full route before moving using 2-opt optimisation. Finds the shortest total distance.<br>
<b>Utility-Based:</b> scores each stop by urgency divided by distance. Reaches ⭐ high-priority stops earlier.
</div>
""", unsafe_allow_html=True)

    if st.session_state.get("playing") and stp < mx:
        time.sleep(1.0 / speed)
        st.session_state["stp"] = stp + 1
        st.rerun()
    elif st.session_state.get("playing") and stp >= mx:
        st.session_state["playing"] = False

# ══════════════════════════════════════════════════════════════════════════════
#  TASK 2 — BIAS  (runs actual task2_segmentation.py functions)
# ══════════════════════════════════════════════════════════════════════════════
with T2:
    st.markdown("""
<div class='step-box'>
<span class='step-num'>?</span><b>What is this?</b><br><br>
EcoCart uses K-Means clustering to group customers into High Value, Medium, and Low Value segments
for targeted marketing. The algorithm was found to be biased — rural customers were almost entirely
placed in Low Value groups even though they are genuine buyers. This task identifies why the bias
exists and applies a fix to make the results fair.
</div>
""", unsafe_allow_html=True)

    st.markdown("<div class='step-box'><span class='step-num'>1</span>"
                "<b>Run the segmentation — click below to execute task2_segmentation.py</b></div>",
                unsafe_allow_html=True)

    run_t2 = st.button("▶  Run Task 2 — Segmentation & Bias Fix", type="primary",
                       use_container_width=True, key="run_t2")

    if run_t2 or st.session_state.get("t2_done"):
        st.session_state["t2_done"] = True

        # import and run the actual task2 logic
        import importlib.util, sys as _sys

        @st.cache_data
        def _run_task2():
            spec = importlib.util.spec_from_file_location(
                "task2", "task2_segmentation.py")
            m = importlib.util.module_from_spec(spec)
            buf = io.StringIO()
            with redirect_stdout(buf):
                spec.loader.exec_module(m)
                m.main()
            return buf.getvalue(), m

        with st.spinner("Running task2_segmentation.py..."):
            t2_output, t2_mod = _run_task2()

        st.markdown("<div class='step-box'><span class='step-num'>2</span>"
                    "<b>Terminal output from task2_segmentation.py</b></div>",
                    unsafe_allow_html=True)
        st.markdown(f"<div class='output-box'>{t2_output}</div>", unsafe_allow_html=True)

        st.markdown("<div class='step-box'><span class='step-num'>3</span>"
                    "<b>Charts saved by task2_segmentation.py</b></div>",
                    unsafe_allow_html=True)

        c1, c2 = st.columns(2)
        with c1:
            if os.path.exists("output/bias_before_after.png"):
                st.image("output/bias_before_after.png",
                         caption="bias_before_after.png — customer clusters before and after mitigation",
                         use_container_width=True)
        with c2:
            if os.path.exists("output/disparate_impact.png"):
                st.image("output/disparate_impact.png",
                         caption="disparate_impact.png — fairness metrics comparison",
                         use_container_width=True)

        st.markdown("""
<div class='insight-box'>
<b>What the output tells us:</b><br><br>
Before the fix: 0% of rural customers were in High Value. Disparate Impact = 0.0 (heavily biased).<br>
After the fix: 57.3% of rural customers are in High Value. Disparate Impact = 0.847 (above the 0.80 fairness threshold).<br><br>
The fix worked by: (1) oversampling rural customers so they have equal representation,
(2) adjusting rural spend for delivery cost and frequency for batching behaviour,
(3) promoting borderline rural customers after re-clustering.
</div>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
#  TASK 3 — ROUTES  (runs actual task3_4_routing.py functions)
# ══════════════════════════════════════════════════════════════════════════════
with T3:
    st.markdown("""
<div class='step-box'>
<span class='step-num'>?</span><b>What is this?</b><br><br>
EcoCart needs to find the shortest delivery route across a network of 20 nodes (10 urban, 10 rural).
Four search algorithms were implemented: BFS, DFS, A*, and IDA*. Each one searches the network
differently. This task runs all four and compares their paths and efficiency. You can also replay
how each algorithm explores the network step by step.
</div>
""", unsafe_allow_html=True)

    st.markdown("<div class='step-box'><span class='step-num'>1</span>"
                "<b>Run all four algorithms — click below to execute task3_4_routing.py</b></div>",
                unsafe_allow_html=True)

    run_t3 = st.button("▶  Run Task 3 — Route Optimisation", type="primary",
                       use_container_width=True, key="run_t3")

    if run_t3 or st.session_state.get("t3_done"):
        st.session_state["t3_done"] = True

        @st.cache_data
        def _run_task3():
            spec = importlib.util.spec_from_file_location(
                "task3", "task3_4_routing.py")
            m = importlib.util.module_from_spec(spec)
            buf = io.StringIO()
            with redirect_stdout(buf):
                spec.loader.exec_module(m)
                m.main()
            return buf.getvalue(), m

        with st.spinner("Running task3_4_routing.py..."):
            t3_output, t3_mod = _run_task3()

        st.markdown("<div class='step-box'><span class='step-num'>2</span>"
                    "<b>Terminal output from task3_4_routing.py</b></div>",
                    unsafe_allow_html=True)
        st.markdown(f"<div class='output-box'>{t3_output}</div>", unsafe_allow_html=True)

        st.markdown("<div class='step-box'><span class='step-num'>3</span>"
                    "<b>Charts saved by task3_4_routing.py</b></div>",
                    unsafe_allow_html=True)

        if os.path.exists("output/network_map.png"):
            st.image("output/network_map.png",
                     caption="network_map.png — the 20-node delivery network",
                     use_container_width=True)
        c1, c2 = st.columns(2)
        with c1:
            if os.path.exists("output/algo_comparison.png"):
                st.image("output/algo_comparison.png",
                         caption="algo_comparison.png — A* vs IDA* across urban and rural routes",
                         use_container_width=True)
        with c2:
            if os.path.exists("output/green_vs_fast.png"):
                st.image("output/green_vs_fast.png",
                         caption="green_vs_fast.png — fastest route vs lowest CO₂ route",
                         use_container_width=True)

        st.markdown("""
<div class='insight-box'>
<b>What the output tells us:</b><br><br>
On route U1→U10: BFS found 5.69 km (11 nodes), DFS found 6.84 km (18 nodes — not optimal),
A* found 5.69 km (only 7 nodes), IDA* found 5.69 km (43 nodes).<br><br>
A* is the recommended algorithm — it always finds the optimal path and checks the fewest nodes.
DFS is the only algorithm that does not guarantee the shortest path.<br><br>
Green routing: A slightly longer path can reduce CO₂ emissions by choosing roads with lower
emission rates (e.g. U1→R9: 14.7 km saves 0.25 kg CO₂ when rerouted to 16.4 km green path).
</div>
""", unsafe_allow_html=True)

    # ── live exploration replay ───────────────────────────────────────────────
    st.markdown("<div class='step-box'><span class='step-num'>4</span>"
                "<b>Interactive: watch an algorithm search the network step by step</b></div>",
                unsafe_allow_html=True)

    # inline network + algorithm for replay
    NODES = {
        "U1":(1.0,1.0,"urban"),  "U2":(2.0,1.5,"urban"),  "U3":(3.0,1.0,"urban"),
        "U4":(1.5,2.5,"urban"),  "U5":(2.5,3.0,"urban"),  "U6":(3.5,2.0,"urban"),
        "U7":(1.0,3.5,"urban"),  "U8":(2.0,4.0,"urban"),  "U9":(3.0,4.0,"urban"),
        "U10":(4.0,3.5,"urban"),
        "R1":(6.0,1.0,"rural"),  "R2":(8.0,2.0,"rural"),  "R3":(10.0,1.5,"rural"),
        "R4":(7.0,4.0,"rural"),  "R5":(9.0,4.5,"rural"),  "R6":(11.0,3.5,"rural"),
        "R7":(6.5,6.0,"rural"),  "R8":(9.0,7.0,"rural"),  "R9":(11.0,6.0,"rural"),
        "R10":(8.0,5.5,"rural"),
    }
    _EP2 = [
        ("U1","U2"),("U2","U3"),("U1","U4"),("U2","U4"),("U2","U5"),
        ("U3","U6"),("U4","U5"),("U5","U6"),("U4","U7"),("U5","U8"),
        ("U6","U10"),("U7","U8"),("U8","U9"),("U9","U10"),("U5","U9"),
        ("R1","R2"),("R2","R3"),("R1","R4"),("R2","R4"),("R3","R6"),
        ("R4","R5"),("R5","R6"),("R4","R7"),("R5","R10"),("R7","R10"),
        ("R7","R8"),("R8","R9"),("R6","R9"),("R8","R10"),("R5","R8"),
        ("U3","R1"),("U10","R4"),("U6","R1"),("U9","R7"),
    ]
    def _nd2(a,b): return math.hypot(NODES[a][0]-NODES[b][0],NODES[a][1]-NODES[b][1])
    EDGES2 = [(a,b,round(_nd2(a,b)*1.15,2)) for a,b in _EP2]
    ADJ2 = {n:[] for n in NODES}
    for a,b,w in EDGES2: ADJ2[a].append((b,w)); ADJ2[b].append((a,w))
    def _ew2(a,b):
        for nb,w in ADJ2[a]:
            if nb==b: return w
        return math.inf

    def _astar_traced(s,g):
        ctr=0; h=lambda n:_nd2(n,g); expl=[]
        heap=[(h(s),0.0,ctr,s,[s])]; best={s:0.0}
        while heap:
            _,gc,_,n,p=heapq.heappop(heap)
            if n==g: return p,round(gc,2),expl
            if gc>best.get(n,math.inf): continue
            expl.append(n)
            for nb,w in ADJ2[n]:
                ng=gc+w
                if ng<best.get(nb,math.inf):
                    best[nb]=ng; ctr+=1
                    heapq.heappush(heap,(ng+h(nb),ng,ctr,nb,p+[nb]))
        return None,0.0,expl

    def _bfs_traced(s,g):
        q=deque([(s,[s])]); seen={s}; expl=[]
        while q:
            n,p=q.popleft(); expl.append(n)
            if n==g: return p,round(sum(_ew2(p[i],p[i+1]) for i in range(len(p)-1)),2),expl
            for nb,_ in ADJ2[n]:
                if nb not in seen: seen.add(nb); q.append((nb,p+[nb]))
        return None,0.0,expl

    rc1, rc2 = st.columns([1, 3])
    with rc1:
        all_n   = list(NODES.keys())
        sn_r    = st.selectbox("Start", all_n, index=0,  key="r_sn")
        en_r    = st.selectbox("End",   all_n, index=19, key="r_en")
        algo_r  = st.radio("Algorithm", ["A*","BFS"], key="r_algo",
                           captions=["Guided, optimal","Level-by-level, optimal"])
        fn_r    = _astar_traced if algo_r == "A*" else _bfs_traced
        if sn_r != en_r:
            path_r, cost_r, expl_r = fn_r(sn_r, en_r)
        else:
            path_r, cost_r, expl_r = [], 0.0, []

    with rc2:
        if sn_r != en_r and expl_r:
            replay = st.slider(
                "Drag to replay the search — see which nodes the algorithm visits",
                0, len(expl_r), len(expl_r), key="replay_sl")
            explored_now = set(expl_r[:replay])
            pct = int(replay / len(expl_r) * 100)
            st.caption(f"{replay}/{len(expl_r)} nodes explored ({pct}%)  "
                       f"{'— path found ✓' if replay == len(expl_r) and path_r else ''}")

            pcol = AMBER
            fn2  = go.Figure()
            for a,b,_ in EDGES2:
                fn2.add_trace(go.Scatter(x=[NODES[a][0],NODES[b][0],None],
                    y=[NODES[a][1],NODES[b][1],None], mode="lines",
                    line=dict(color="#e2e8f0",width=1.5), showlegend=False, hoverinfo="skip"))
            if path_r and replay == len(expl_r):
                for i in range(len(path_r)-1):
                    a,b=path_r[i],path_r[i+1]
                    fn2.add_trace(go.Scatter(x=[NODES[a][0],NODES[b][0],None],
                        y=[NODES[a][1],NODES[b][1],None], mode="lines",
                        line=dict(color=pcol,width=5), showlegend=False, hoverinfo="skip"))
            ps = set(path_r) if path_r else set()
            for zone, bc in [("urban",RED),("rural",GREEN)]:
                ns = [(n,d) for n,d in NODES.items() if d[2]==zone]
                cols = ["#fff" if n==sn_r else "#facc15" if n==en_r
                        else pcol if n in ps
                        else "#bfdbfe" if n in explored_now
                        else bc for n,_ in ns]
                fn2.add_trace(go.Scatter(
                    x=[d[0] for _,d in ns], y=[d[1] for _,d in ns],
                    mode="markers+text", name=zone.title(),
                    marker=dict(size=22, color=cols, line=dict(color=FG,width=1.5)),
                    text=[n for n,_ in ns], textposition="middle center",
                    textfont=dict(size=8,color=FG),
                    hovertemplate="<b>%{text}</b><extra></extra>"))
            fn2.update_layout(**_ch(460, f"{algo_r}: {sn_r} → {en_r}"))
            fn2.update_xaxes(showgrid=False, showticklabels=False, zeroline=False)
            fn2.update_yaxes(showgrid=False, showticklabels=False, zeroline=False)
            st.plotly_chart(fn2, use_container_width=True, key="route_replay")

            lc = st.columns(4)
            lc[0].markdown(f"<span style='color:{RED}'>⬤</span> Urban", unsafe_allow_html=True)
            lc[1].markdown(f"<span style='color:{GREEN}'>⬤</span> Rural", unsafe_allow_html=True)
            lc[2].markdown("<span style='color:#bfdbfe'>⬤</span> Explored", unsafe_allow_html=True)
            lc[3].markdown(f"<span style='color:{AMBER}'>⬤</span> Final path", unsafe_allow_html=True)

            if path_r and replay == len(expl_r):
                mc = st.columns(3)
                mc[0].metric("Path cost", f"{cost_r:.2f} km")
                mc[1].metric("Nodes explored", len(expl_r))
                mc[2].metric("Path", " → ".join(path_r))

# ══════════════════════════════════════════════════════════════════════════════
#  TASK 4 — A* vs IDA* benchmark (from task3_4_routing.py output)
# ══════════════════════════════════════════════════════════════════════════════
with T4:
    st.markdown("""
<div class='step-box'>
<span class='step-num'>?</span><b>What is this?</b><br><br>
Both A* and IDA* find the optimal route, but they work differently. A* stores all explored
nodes in memory (fast but uses more RAM). IDA* uses almost no memory by re-searching with
a stricter cost limit each time. This task runs both algorithms on 10 real delivery routes
and compares their speed and the number of nodes they check.
</div>
""", unsafe_allow_html=True)

    st.markdown("<div class='step-box'><span class='step-num'>1</span>"
                "<b>Results from task3_4_routing.py — the benchmark ran 20 times per route</b></div>",
                unsafe_allow_html=True)

    urban_data = [
        ["U1→U10", "5.69", "7",  "0.170", "5.69", "43", "0.559"],
        ["U7→U6",  "4.21", "5",  "0.088", "4.21", "22", "0.472"],
        ["U2→U9",  "3.11", "2",  "0.073", "3.11", "6",  "0.129"],
        ["U1→U9",  "4.40", "4",  "0.088", "4.40", "15", "0.223"],
        ["U3→U8",  "4.21", "5",  "0.114", "4.21", "19", "0.283"],
    ]
    rural_data = [
        ["R1→R9",  "10.39","6",  "0.134", "10.39","34", "0.466"],
        ["R2→R8",  "7.82", "4",  "0.101", "7.82", "14", "0.224"],
        ["R3→R10", "6.77", "5",  "0.107", "6.77", "21", "0.279"],
        ["R1→R6",  "7.51", "3",  "0.065", "7.51", "10", "0.149"],
        ["R4→R9",  "7.82", "7",  "0.130", "7.82", "50", "0.642"],
    ]
    headers = ["Route","A* km","A* nodes","A* ms","IDA* km","IDA* nodes","IDA* ms"]

    cu, cr = st.columns(2)
    with cu:
        st.markdown("**Urban routes (U cluster)**")
        st.dataframe(pd.DataFrame(urban_data, columns=headers),
                     use_container_width=True, hide_index=True)
    with cr:
        st.markdown("**Rural routes (R cluster)**")
        st.dataframe(pd.DataFrame(rural_data, columns=headers),
                     use_container_width=True, hide_index=True)

    st.markdown("<div class='step-box'><span class='step-num'>2</span>"
                "<b>Chart from task3_4_routing.py</b></div>", unsafe_allow_html=True)
    if os.path.exists("output/algo_comparison.png"):
        st.image("output/algo_comparison.png",
                 caption="algo_comparison.png — generated by task3_4_routing.py",
                 use_container_width=True)

    st.markdown("<div class='step-box'><span class='step-num'>3</span>"
                "<b>Interactive comparison</b></div>", unsafe_allow_html=True)

    all_rows = urban_data + rural_data
    routes   = [r[0] for r in all_rows]
    a_nodes  = [int(r[2]) for r in all_rows]
    i_nodes  = [int(r[5]) for r in all_rows]
    a_ms     = [float(r[3]) for r in all_rows]
    i_ms     = [float(r[6]) for r in all_rows]

    fig_cmp = make_subplots(rows=1, cols=2,
                            subplot_titles=["Nodes expanded (fewer = smarter)",
                                            "Time in ms (lower = faster)"])
    for ci, (av, iv, label) in enumerate([(a_nodes,i_nodes,"Nodes expanded"),
                                           (a_ms,   i_ms,   "Time (ms)")], 1):
        fig_cmp.add_trace(go.Bar(name="A*",   x=routes, y=av, marker_color=BLUE,
                                 showlegend=(ci==1)), row=1, col=ci)
        fig_cmp.add_trace(go.Bar(name="IDA*", x=routes, y=iv, marker_color=AMBER,
                                 showlegend=(ci==1)), row=1, col=ci)
    fig_cmp.update_layout(paper_bgcolor=SURF, plot_bgcolor=BG, font_color=FG,
                          barmode="group", height=360,
                          margin=dict(l=40,r=20,t=50,b=80),
                          legend=dict(bgcolor=SURF,bordercolor=LINE))
    fig_cmp.update_xaxes(gridcolor=LINE, tickangle=45)
    fig_cmp.update_yaxes(gridcolor=LINE)
    st.plotly_chart(fig_cmp, use_container_width=True)

    st.markdown("""
<div class='insight-box'>
<b>What the output tells us:</b><br><br>
Both algorithms found <b>identical optimal paths</b> on every single route — the costs match exactly.<br><br>
A* expanded fewer nodes in every case. For example on R4→R9: A* checked 7 nodes, IDA* checked 50.<br>
A* was also faster in ms on this 20-node graph.<br><br>
However, IDA* uses almost no memory (O(depth)) while A* stores all explored nodes (O(b^d)).
On a national road network with millions of nodes, IDA* would be the only practical choice.
</div>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
#  TASK 5 — FORECASTING  (runs actual task5_forecasting.py)
# ══════════════════════════════════════════════════════════════════════════════
with T5:
    st.markdown("""
<div class='step-box'>
<span class='step-num'>?</span><b>What is this?</b><br><br>
EcoCart wants to predict how many units it will sell each day so it can stock the right
amount of inventory. This task trains two machine learning models — Linear Regression and
Random Forest — on 730 days of sales data and evaluates which one predicts more accurately
on 140 unseen test days.
</div>
""", unsafe_allow_html=True)

    st.markdown("<div class='step-box'><span class='step-num'>1</span>"
                "<b>Run the forecast — click below to execute task5_forecasting.py</b></div>",
                unsafe_allow_html=True)

    run_t5 = st.button("▶  Run Task 5 — Demand Forecasting", type="primary",
                       use_container_width=True, key="run_t5")

    if run_t5 or st.session_state.get("t5_done"):
        st.session_state["t5_done"] = True

        @st.cache_data
        def _run_task5():
            spec = importlib.util.spec_from_file_location(
                "task5", "task5_forecasting.py")
            m = importlib.util.module_from_spec(spec)
            buf = io.StringIO()
            with redirect_stdout(buf):
                spec.loader.exec_module(m)
                m.main()
            return buf.getvalue()

        with st.spinner("Running task5_forecasting.py..."):
            t5_output = _run_task5()

        st.markdown("<div class='step-box'><span class='step-num'>2</span>"
                    "<b>Terminal output from task5_forecasting.py</b></div>",
                    unsafe_allow_html=True)
        st.markdown(f"<div class='output-box'>{t5_output}</div>", unsafe_allow_html=True)

        st.markdown("<div class='step-box'><span class='step-num'>3</span>"
                    "<b>Charts saved by task5_forecasting.py</b></div>",
                    unsafe_allow_html=True)

        if os.path.exists("output/forecast.png"):
            st.image("output/forecast.png",
                     caption="forecast.png — actual vs predicted daily sales on the test set",
                     use_container_width=True)

        c1, c2 = st.columns(2)
        with c1:
            if os.path.exists("output/residuals.png"):
                st.image("output/residuals.png",
                         caption="residuals.png — prediction errors for both models",
                         use_container_width=True)
        with c2:
            if os.path.exists("output/feature_importance.png"):
                st.image("output/feature_importance.png",
                         caption="feature_importance.png — which features matter most",
                         use_container_width=True)

        st.markdown("""
<div class='step-box'><span class='step-num'>4</span>
<b>Metrics from the actual run</b></div>
""", unsafe_allow_html=True)

        mc = st.columns(4)
        mc[0].metric("LR — MAE",  "9.62 units")
        mc[1].metric("LR — R²",   "0.762")
        mc[2].metric("RF — MAE",  "9.75 units")
        mc[3].metric("RF — R²",   "0.716")

        st.markdown("""
<div class='insight-box'>
<b>What the output tells us:</b><br><br>
Linear Regression achieved R² = 0.762, meaning it explains 76.2% of the variation in daily sales.
Random Forest achieved R² = 0.716. On this dataset, Linear Regression performed slightly better.<br><br>
The top 3 most important features were: <b>lag_7</b> (sales 7 days ago), <b>lag_14</b>, and <b>is_promo</b>.
This confirms that weekly sales patterns and promotional activity are the strongest predictors of demand.
</div>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
#  TASK 6 — BUSINESS CASE
# ══════════════════════════════════════════════════════════════════════════════
with T6:
    st.markdown("""
<div class='step-box'>
<span class='step-num'>?</span><b>What is this?</b><br><br>
This task is attempted voluntarily (AI students are permitted to do so).
It estimates the business value and environmental impact of deploying the AI system.
<br><br>
<b>Important:</b> All numbers here are <em>assumptions for illustration</em>, not measured values.
Adjust the sliders to model different scenarios.
</div>
""", unsafe_allow_html=True)

    c_ctrl, c_main = st.columns([1, 3])

    with c_ctrl:
        st.markdown("**Your assumptions**")
        fleet    = st.slider("Fleet (vehicles)",      5,  100, 30,  5)
        daily    = st.slider("Deliveries/vehicle/day",10,  80, 40,  5)
        avg_km   = st.slider("Avg km per delivery",   2,   30, 12,  1)
        fuel     = st.slider("Fuel €/km",           0.10,0.60,0.32,0.01, format="€%.2f")
        wage     = st.slider("Driver wage €/hr",      10,  35, 18,  1,   format="€%d")
        days_yr  = st.slider("Working days/year",    200, 365,300, 10)
        rt_save  = st.slider("Route saving % (A*)",   5,  35, 18,  1,   format="%d%%")
        seg_rev  = st.slider("Rural revenue uplift €k", 10, 200, 65, 5)

    with c_main:
        total_km   = fleet * daily * days_yr * avg_km
        km_saved   = total_km * rt_save / 100
        fuel_saved = km_saved * fuel
        time_saved = (km_saved / 40) * wage
        route_save = fuel_saved + time_saved
        seg_save   = seg_rev * 1000
        total_eur  = route_save + seg_save
        co2        = km_saved * 0.24 / 1000
        dev        = 45000; ops = 8000
        payback    = round((dev + ops) / total_eur * 12, 1) if total_eur > 0 else 0
        roi3       = round((total_eur*3 - (dev+ops*3)) / (dev+ops*3) * 100, 1)

        mc = st.columns(4)
        mc[0].metric("Est. annual saving", f"€{round(total_eur/1000,1)}k")
        mc[1].metric("Est. payback",       f"{payback} months")
        mc[2].metric("3-year ROI",         f"{roi3}%")
        mc[3].metric("CO₂ saved/year",     f"{co2:.1f} tonnes")

        cats = ["Route Optimisation\n(A*)","Fairer Segmentation\n(rural uplift)"]
        vals = [round(route_save/1000,1), round(seg_save/1000,1)]
        fig_b = go.Figure(go.Bar(x=cats, y=vals, marker_color=[BLUE, GREEN],
                                 text=[f"€{v}k" for v in vals], textposition="outside",
                                 textfont_color=FG, width=0.4))
        fig_b.update_layout(**_ch(260, "Estimated annual savings by area (€ thousands)"))
        fig_b.update_xaxes(gridcolor=LINE)
        fig_b.update_yaxes(gridcolor=LINE, title="€ thousands")
        st.plotly_chart(fig_b, use_container_width=True)

        years = [0,1,2,3]
        benefit = [0, total_eur, total_eur*2, total_eur*3]
        cost    = [0, dev+ops, dev+ops*2, dev+ops*3]
        fig_r = go.Figure()
        fig_r.add_trace(go.Scatter(x=years, y=[v/1000 for v in benefit],
            name="Cumulative benefit", line=dict(color=GREEN, width=2.5), mode="lines+markers"))
        fig_r.add_trace(go.Scatter(x=years, y=[v/1000 for v in cost],
            name="Cumulative cost", line=dict(color=RED, width=2.5, dash="dash"), mode="lines+markers"))
        fig_r.add_hline(y=0, line_color=MUTE, line_width=1, line_dash="dot")
        fig_r.update_layout(**_ch(280, "3-year ROI projection (€ thousands, assumed values)"))
        fig_r.update_xaxes(gridcolor=LINE, tickvals=[0,1,2,3],
                           ticktext=["Now","Year 1","Year 2","Year 3"])
        fig_r.update_yaxes(gridcolor=LINE, title="€ thousands")
        st.plotly_chart(fig_r, use_container_width=True)

        st.markdown(
            f"<div class='warn-box'>"
            f"All numbers are <b>estimated assumptions</b> for illustrative purposes only. "
            f"They are not measured from the simulation. "
            f"Based on your inputs: {fleet} vehicles, {daily} deliveries/day, {avg_km} km avg, "
            f"{rt_save}% route saving from A*, €{seg_rev}k rural revenue uplift."
            f"</div>", unsafe_allow_html=True)
